"""empty message

Revision ID: 00fbad286ee6
Revises: e2357207b91e
Create Date: 2022-11-10 13:07:35.130366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00fbad286ee6'
down_revision = 'e2357207b91e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weeklies',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('character', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('week', sa.SMALLINT(), nullable=True),
    sa.Column('is_prev_week', sa.BOOLEAN(), nullable=True),
    sa.Column('weeklies_list', sa.VARCHAR(length=50), nullable=True),
    sa.Column('weeklies_done', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weeklies')
    # ### end Alembic commands ###
