"""empty message

Revision ID: 08a5333d164f
Revises: 6d38dfb42d90
Create Date: 2022-11-12 11:18:20.468476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08a5333d164f'
down_revision = '6d38dfb42d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farming',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('character', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('first_day_of_week', sa.DATE(), nullable=True),
    sa.Column('is_current_week', sa.BOOLEAN(), nullable=True),
    sa.Column('hours', sa.SMALLINT(), nullable=True),
    sa.Column('minutes', sa.SMALLINT(), nullable=True),
    sa.Column('mesos', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farming')
    # ### end Alembic commands ###
