"""empty message

Revision ID: 165d930c819f
Revises: 
Create Date: 2022-11-12 18:42:18.910778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '165d930c819f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('region', sa.VARCHAR(length=20), nullable=True),
    sa.Column('slot', sa.VARCHAR(length=20), nullable=True),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['region'], ['roles_enum.roles'], ),
    sa.ForeignKeyConstraint(['slot'], ['slots_enum.slots'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('progression_gear',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('character', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('slot', sa.VARCHAR(length=20), nullable=True),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('starforce', sa.SMALLINT(), nullable=True),
    sa.Column('flame_score', sa.SMALLINT(), nullable=True),
    sa.Column('pot_mainstat', sa.SMALLINT(), nullable=True),
    sa.Column('pot_allstats', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.uuid'], ),
    sa.ForeignKeyConstraint(['slot'], ['slots_enum.slots'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('progression_secondary_emblem',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('character', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('slot', sa.VARCHAR(length=20), nullable=True),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('starforce', sa.SMALLINT(), nullable=True),
    sa.Column('pot_att', sa.SMALLINT(), nullable=True),
    sa.Column('pot_boss', sa.SMALLINT(), nullable=True),
    sa.Column('pot_ied', sa.SMALLINT(), nullable=True),
    sa.Column('pot_mainstat', sa.SMALLINT(), nullable=True),
    sa.Column('pot_allstats', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.uuid'], ),
    sa.ForeignKeyConstraint(['slot'], ['slots_enum.slots'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('progression_single_field',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('character', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('slot', sa.VARCHAR(length=20), nullable=True),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('value', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.uuid'], ),
    sa.ForeignKeyConstraint(['slot'], ['slots_enum.slots'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('progression_weapons',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('character', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('starforce', sa.SMALLINT(), nullable=True),
    sa.Column('pot_att', sa.SMALLINT(), nullable=True),
    sa.Column('pot_boss', sa.SMALLINT(), nullable=True),
    sa.Column('pot_ied', sa.SMALLINT(), nullable=True),
    sa.Column('pot_mainstat', sa.SMALLINT(), nullable=True),
    sa.Column('pot_allstats', sa.SMALLINT(), nullable=True),
    sa.Column('flame_att', sa.SMALLINT(), nullable=True),
    sa.Column('flame_boss', sa.SMALLINT(), nullable=True),
    sa.Column('flame_dmg', sa.SMALLINT(), nullable=True),
    sa.Column('flame_allstats', sa.SMALLINT(), nullable=True),
    sa.Column('flame_mainstat', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.drop_table('item_names_enum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_names_enum',
    sa.Column('item_names', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('item_names', name='item_names_enum_pkey')
    )
    op.drop_table('progression_weapons')
    op.drop_table('progression_single_field')
    op.drop_table('progression_secondary_emblem')
    op.drop_table('progression_gear')
    op.drop_table('items')
    # ### end Alembic commands ###
