"""empty message

Revision ID: 1ba6a61a4d2b
Revises: ae963039e3fb
Create Date: 2022-11-11 02:09:08.577467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ba6a61a4d2b'
down_revision = 'ae963039e3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('main', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'users', 'characters', ['main'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'main')
    # ### end Alembic commands ###
