"""empty message

Revision ID: 1f21ff2267b2
Revises: 64026854ca13
Create Date: 2022-11-10 14:12:09.315494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f21ff2267b2'
down_revision = '64026854ca13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailies',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('character', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('is_prev_day', sa.BOOLEAN(), nullable=True),
    sa.Column('dailies_list', sa.TEXT(), nullable=True),
    sa.Column('dailies_done', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dailies')
    # ### end Alembic commands ###
