"""empty message

Revision ID: 20982d8acd58
Revises: 9c2210683843
Create Date: 2022-11-12 13:25:57.128459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20982d8acd58'
down_revision = '9c2210683843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ursus_tour',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('first_day_of_bossing_week', sa.DATE(), nullable=True),
    sa.Column('ursus', sa.INTEGER(), nullable=True),
    sa.Column('tour', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('weekly_mesos',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=True),
    sa.Column('first_day_of_bossing_week', sa.DATE(), nullable=True),
    sa.Column('ursus', sa.BIGINT(), nullable=True),
    sa.Column('tour', sa.BIGINT(), nullable=True),
    sa.Column('bossing', sa.BIGINT(), nullable=True),
    sa.Column('farming', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('bossing',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('character', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('first_day_of_bossing_week', sa.DATE(), nullable=True),
    sa.Column('is_current_week', sa.BOOLEAN(), nullable=True),
    sa.Column('bossing_list', sa.TEXT(), nullable=True),
    sa.Column('bossing_done', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('farming',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('character', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('first_day_of_week', sa.DATE(), nullable=True),
    sa.Column('first_day_of_bossing_week', sa.DATE(), nullable=True),
    sa.Column('is_current_week', sa.BOOLEAN(), nullable=True),
    sa.Column('hours', sa.SMALLINT(), nullable=True),
    sa.Column('minutes', sa.SMALLINT(), nullable=True),
    sa.Column('mesos', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farming')
    op.drop_table('bossing')
    op.drop_table('weekly_mesos')
    op.drop_table('ursus_tour')
    # ### end Alembic commands ###
