"""empty message

Revision ID: 2a7d707ee188
Revises: a79252f344ae
Create Date: 2022-11-11 20:32:21.552912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a7d707ee188'
down_revision = 'a79252f344ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_character_shops',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('region', sa.VARCHAR(length=20), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=20), nullable=True),
    sa.Column('item', sa.VARCHAR(length=30), nullable=True),
    sa.Column('cost', sa.SMALLINT(), nullable=True),
    sa.Column('quantity', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['region'], ['roles_enum.roles'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('events_main',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('region', sa.VARCHAR(length=20), nullable=True),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['region'], ['roles_enum.roles'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('events_sub',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('region', sa.VARCHAR(length=20), nullable=True),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['region'], ['roles_enum.roles'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('events_world_shops',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('region', sa.VARCHAR(length=20), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=20), nullable=True),
    sa.Column('item', sa.VARCHAR(length=30), nullable=True),
    sa.Column('cost', sa.SMALLINT(), nullable=True),
    sa.Column('quantity', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['region'], ['roles_enum.roles'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.drop_table('events_main_gms')
    op.drop_table('events_character_shops_msea')
    op.drop_table('events_main_msea')
    op.drop_table('events_world_shops_gms')
    op.drop_table('events_sub_msea')
    op.drop_table('events_sub_gms')
    op.drop_table('events_world_shops_msea')
    op.drop_table('events_character_shops_gms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_character_shops_gms',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('item', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('cost', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='events_character_shops_gms_pkey')
    )
    op.create_table('events_world_shops_msea',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('item', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('cost', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='events_world_shops_msea_pkey')
    )
    op.create_table('events_sub_gms',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='events_sub_gms_pkey')
    )
    op.create_table('events_sub_msea',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='events_sub_msea_pkey')
    )
    op.create_table('events_world_shops_gms',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('item', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('cost', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='events_world_shops_gms_pkey')
    )
    op.create_table('events_main_msea',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='events_main_msea_pkey')
    )
    op.create_table('events_character_shops_msea',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('item', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('cost', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='events_character_shops_msea_pkey')
    )
    op.create_table('events_main_gms',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='events_main_gms_pkey')
    )
    op.drop_table('events_world_shops')
    op.drop_table('events_sub')
    op.drop_table('events_main')
    op.drop_table('events_character_shops')
    # ### end Alembic commands ###
