"""empty message

Revision ID: 515e614719c7
Revises: e697e35aa577
Create Date: 2022-11-09 16:22:04.649943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515e614719c7'
down_revision = 'e697e35aa577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes_enum',
    sa.Column('classes', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('classes')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classes_enum')
    # ### end Alembic commands ###
