"""empty message

Revision ID: 568a73cc8170
Revises: 515e614719c7
Create Date: 2022-11-09 16:52:41.351660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '568a73cc8170'
down_revision = '515e614719c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=True),
    sa.Column('class_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('ign', sa.VARCHAR(length=12), nullable=True),
    sa.Column('level', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['class_name'], ['classes_enum.classes'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
