"""empty message

Revision ID: 58ccd652fc76
Revises: 
Create Date: 2022-12-10 23:51:42.993902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58ccd652fc76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bosses',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('id', sa.SMALLINT(), nullable=True),
    sa.Column('region', sa.VARCHAR(length=20), nullable=True),
    sa.Column('name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('crystal', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['region'], ['roles_enum.roles'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bosses')
    # ### end Alembic commands ###
