"""empty message

Revision ID: 6d38dfb42d90
Revises: 4516c592a999
Create Date: 2022-11-12 00:36:32.573127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d38dfb42d90'
down_revision = '4516c592a999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_world_currency',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=20), nullable=True),
    sa.Column('amount', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('user_world_shops',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=20), nullable=True),
    sa.Column('item', sa.VARCHAR(length=30), nullable=True),
    sa.Column('cost', sa.SMALLINT(), nullable=True),
    sa.Column('quantity', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('user_character_currency',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('character', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=20), nullable=True),
    sa.Column('amount', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('user_character_shops',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('character', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=20), nullable=True),
    sa.Column('item', sa.VARCHAR(length=30), nullable=True),
    sa.Column('cost', sa.SMALLINT(), nullable=True),
    sa.Column('quantity', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_character_shops')
    op.drop_table('user_character_currency')
    op.drop_table('user_world_shops')
    op.drop_table('user_world_currency')
    # ### end Alembic commands ###
