"""empty message

Revision ID: 740959488467
Revises: 568a73cc8170
Create Date: 2022-11-10 11:07:32.856731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '740959488467'
down_revision = '568a73cc8170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ursus_tour',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('ursus', sa.INTEGER(), nullable=True),
    sa.Column('tour', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('dailies',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('character', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('is_prev_day', sa.BOOLEAN(), nullable=True),
    sa.Column('dailies_list', sa.VARCHAR(length=50), nullable=True),
    sa.Column('dailies_done', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('weeklies',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('character', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('is_prev_week', sa.BOOLEAN(), nullable=True),
    sa.Column('weeklies_list', sa.VARCHAR(length=50), nullable=True),
    sa.Column('weeklies_done', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weeklies')
    op.drop_table('dailies')
    op.drop_table('ursus_tour')
    # ### end Alembic commands ###
