"""empty message

Revision ID: 7d327e2bf073
Revises: 1f21ff2267b2
Create Date: 2022-11-10 15:12:41.915210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d327e2bf073'
down_revision = '1f21ff2267b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weeklies',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('character', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('week', sa.SMALLINT(), nullable=True),
    sa.Column('is_prev_week', sa.BOOLEAN(), nullable=True),
    sa.Column('weeklies_list', sa.TEXT(), nullable=True),
    sa.Column('weeklies_done', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.drop_table('ursus_tour')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ursus_tour',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('ursus', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tour', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], name='ursus_tour_username_fkey'),
    sa.PrimaryKeyConstraint('uuid', name='ursus_tour_pkey')
    )
    op.drop_table('weeklies')
    # ### end Alembic commands ###
