"""empty message

Revision ID: 7e8002b621d7
Revises: 034def11cd98
Create Date: 2022-11-10 17:09:35.435484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8002b621d7'
down_revision = '034def11cd98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailies_default',
    sa.Column('dailies_list', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('dailies_list')
    )
    op.create_table('weeklies_default',
    sa.Column('weeklies_list', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('weeklies_list')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weeklies_default')
    op.drop_table('dailies_default')
    # ### end Alembic commands ###
