"""empty message

Revision ID: 7f82db2e48a6
Revises: e34690e72e81
Create Date: 2022-11-12 17:30:26.432102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f82db2e48a6'
down_revision = 'e34690e72e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progression_single_field',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('character', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('slot', sa.VARCHAR(length=20), nullable=True),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('value', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.uuid'], ),
    sa.ForeignKeyConstraint(['name'], ['item_names_enum.item_names'], ),
    sa.ForeignKeyConstraint(['slot'], ['slots_enum.slots'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progression_single_field')
    # ### end Alembic commands ###
