"""empty message

Revision ID: 83a0bf5d78b3
Revises: 165d930c819f
Create Date: 2022-11-14 18:34:52.194264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a0bf5d78b3'
down_revision = '165d930c819f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes_enum', sa.Column('region', sa.VARCHAR(length=20), nullable=True))
    op.create_foreign_key(None, 'classes_enum', 'roles_enum', ['region'], ['roles'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classes_enum', type_='foreignkey')
    op.drop_column('classes_enum', 'region')
    # ### end Alembic commands ###
