"""empty message

Revision ID: 951493dc22a2
Revises: 069dc58729c4
Create Date: 2022-11-12 16:14:14.585438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '951493dc22a2'
down_revision = '069dc58729c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_names_enum',
    sa.Column('item_names', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('item_names')
    )
    op.create_table('slots_enum',
    sa.Column('slots', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('slots')
    )
    op.create_table('progression_gear',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('character', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('slot', sa.VARCHAR(length=20), nullable=True),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('starforce', sa.SMALLINT(), nullable=True),
    sa.Column('flame_score', sa.SMALLINT(), nullable=True),
    sa.Column('pot_mainstat', sa.SMALLINT(), nullable=True),
    sa.Column('pot_allstats', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.uuid'], ),
    sa.ForeignKeyConstraint(['name'], ['item_names_enum.item_names'], ),
    sa.ForeignKeyConstraint(['slot'], ['slots_enum.slots'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('progression_one_field',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('character', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('slot', sa.VARCHAR(length=20), nullable=True),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('value', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.uuid'], ),
    sa.ForeignKeyConstraint(['name'], ['item_names_enum.item_names'], ),
    sa.ForeignKeyConstraint(['slot'], ['slots_enum.slots'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('progression_secondary_emblem',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('character', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('slot', sa.VARCHAR(length=20), nullable=True),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('starforce', sa.SMALLINT(), nullable=True),
    sa.Column('pot_att', sa.SMALLINT(), nullable=True),
    sa.Column('pot_boss', sa.SMALLINT(), nullable=True),
    sa.Column('pot_ied', sa.SMALLINT(), nullable=True),
    sa.Column('pot_mainstat', sa.SMALLINT(), nullable=True),
    sa.Column('pot_allstats', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.uuid'], ),
    sa.ForeignKeyConstraint(['name'], ['item_names_enum.item_names'], ),
    sa.ForeignKeyConstraint(['slot'], ['slots_enum.slots'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('progression_weapons',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('character', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('starforce', sa.SMALLINT(), nullable=True),
    sa.Column('pot_att', sa.SMALLINT(), nullable=True),
    sa.Column('pot_boss', sa.SMALLINT(), nullable=True),
    sa.Column('pot_ied', sa.SMALLINT(), nullable=True),
    sa.Column('pot_mainstat', sa.SMALLINT(), nullable=True),
    sa.Column('pot_allstats', sa.SMALLINT(), nullable=True),
    sa.Column('flame_att', sa.SMALLINT(), nullable=True),
    sa.Column('flame_boss', sa.SMALLINT(), nullable=True),
    sa.Column('flame_dmg', sa.SMALLINT(), nullable=True),
    sa.Column('flame_allstats', sa.SMALLINT(), nullable=True),
    sa.Column('flame_mainstat', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.uuid'], ),
    sa.ForeignKeyConstraint(['name'], ['item_names_enum.item_names'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progression_weapons')
    op.drop_table('progression_secondary_emblem')
    op.drop_table('progression_one_field')
    op.drop_table('progression_gear')
    op.drop_table('slots_enum')
    op.drop_table('item_names_enum')
    # ### end Alembic commands ###
