"""empty message

Revision ID: 9c2210683843
Revises: 08a5333d164f
Create Date: 2022-11-12 12:58:19.366938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c2210683843'
down_revision = '08a5333d164f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_mesos',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=True),
    sa.Column('first_day_of_week', sa.DATE(), nullable=True),
    sa.Column('ursus', sa.BIGINT(), nullable=True),
    sa.Column('tour', sa.BIGINT(), nullable=True),
    sa.Column('bossing', sa.BIGINT(), nullable=True),
    sa.Column('farming', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.add_column('ursus_tour', sa.Column('first_day_of_week', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ursus_tour', 'first_day_of_week')
    op.drop_table('weekly_mesos')
    # ### end Alembic commands ###
