"""empty message

Revision ID: a1fe15a7977d
Revises: 67a56fe38b84
Create Date: 2022-11-09 14:57:55.884905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1fe15a7977d'
down_revision = '67a56fe38b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('pw_hash', sa.VARCHAR(length=70), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['roles_enum.roles'], ),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
