"""empty message

Revision ID: a79252f344ae
Revises: ab4344b4e109
Create Date: 2022-11-11 20:15:12.603852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a79252f344ae'
down_revision = 'ab4344b4e109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_character_shops_gms',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=20), nullable=True),
    sa.Column('item', sa.VARCHAR(length=30), nullable=True),
    sa.Column('cost', sa.SMALLINT(), nullable=True),
    sa.Column('quantity', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('events_character_shops_msea',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=20), nullable=True),
    sa.Column('item', sa.VARCHAR(length=30), nullable=True),
    sa.Column('cost', sa.SMALLINT(), nullable=True),
    sa.Column('quantity', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('events_main_gms',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('events_main_msea',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('events_sub_gms',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('events_sub_msea',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('events_world_shops_gms',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=20), nullable=True),
    sa.Column('item', sa.VARCHAR(length=30), nullable=True),
    sa.Column('cost', sa.SMALLINT(), nullable=True),
    sa.Column('quantity', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('events_world_shops_msea',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=20), nullable=True),
    sa.Column('item', sa.VARCHAR(length=30), nullable=True),
    sa.Column('cost', sa.SMALLINT(), nullable=True),
    sa.Column('quantity', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('bosses',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('crystal', sa.BIGINT(), nullable=True),
    sa.Column('region', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['region'], ['roles_enum.roles'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bosses_gms')
    op.drop_table('bosses_msea')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bosses_msea',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('bosses_msea_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('crystal', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bosses_msea_pkey')
    )
    op.create_table('bosses_gms',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('bosses_gms_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('crystal', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bosses_gms_pkey')
    )
    op.drop_table('bosses')
    op.drop_table('events_world_shops_msea')
    op.drop_table('events_world_shops_gms')
    op.drop_table('events_sub_msea')
    op.drop_table('events_sub_gms')
    op.drop_table('events_main_msea')
    op.drop_table('events_main_gms')
    op.drop_table('events_character_shops_msea')
    op.drop_table('events_character_shops_gms')
    # ### end Alembic commands ###
