"""empty message

Revision ID: ab4344b4e109
Revises: 1ba6a61a4d2b
Create Date: 2022-11-11 11:21:19.608735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4344b4e109'
down_revision = '1ba6a61a4d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_enum',
    sa.Column('tracking', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('tracking')
    )
    op.add_column('characters', sa.Column('tracking', sa.VARCHAR(length=20), nullable=True))
    op.create_foreign_key(None, 'characters', 'tracking_enum', ['tracking'], ['tracking'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_column('characters', 'tracking')
    op.drop_table('tracking_enum')
    # ### end Alembic commands ###
