"""empty message

Revision ID: ae963039e3fb
Revises: bf2277184d7c
Create Date: 2022-11-11 01:41:29.652876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae963039e3fb'
down_revision = 'bf2277184d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legion',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=True),
    sa.Column('class_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('level', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['class_name'], ['classes_enum.classes'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('legion')
    # ### end Alembic commands ###
