"""empty message

Revision ID: b2a7cead378a
Revises: 
Create Date: 2022-12-10 23:57:09.216898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a7cead378a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bosses',
    sa.Column('primary', sa.SMALLINT(), nullable=False),
    sa.Column('id', sa.SMALLINT(), nullable=True),
    sa.Column('region', sa.VARCHAR(length=20), nullable=True),
    sa.Column('name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('crystal', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['region'], ['roles_enum.roles'], ),
    sa.PrimaryKeyConstraint('primary')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bosses')
    # ### end Alembic commands ###
