"""empty message

Revision ID: c40c3c9b8c8c
Revises: a1fe15a7977d
Create Date: 2022-11-09 15:05:49.489552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40c3c9b8c8c'
down_revision = 'a1fe15a7977d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('pw_hash', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['roles_enum.roles'], ),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
