"""empty message

Revision ID: d820c2b25c89
Revises: 
Create Date: 2022-11-09 13:02:34.692465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd820c2b25c89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_enum',
    sa.Column('roles', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('roles')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=40), nullable=True),
    sa.Column('lname', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('password', sa.VARCHAR(length=60), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['roles_enum.roles'], ),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('students')
    op.drop_table('roles_enum')
    # ### end Alembic commands ###
