"""empty message

Revision ID: e2357207b91e
Revises: 740959488467
Create Date: 2022-11-10 11:27:48.928268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2357207b91e'
down_revision = '740959488467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weeklies',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('character', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('week_starting_from', sa.DATE(), nullable=True),
    sa.Column('is_prev_week', sa.BOOLEAN(), nullable=True),
    sa.Column('weeklies_list', sa.VARCHAR(length=50), nullable=True),
    sa.Column('weeklies_done', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weeklies')
    # ### end Alembic commands ###
