"""empty message

Revision ID: e697e35aa577
Revises: 4fea8cbd34f9
Create Date: 2022-11-09 15:36:21.311919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e697e35aa577'
down_revision = '4fea8cbd34f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('pw_hash', sa.VARCHAR(length=60), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['roles_enum.roles'], ),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
