"""empty message

Revision ID: f052c4c4c34b
Revises: 
Create Date: 2022-11-16 17:11:35.238030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f052c4c4c34b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=True),
    sa.Column('class_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('ign', sa.VARCHAR(length=12), nullable=True),
    sa.Column('level', sa.SMALLINT(), nullable=True),
    sa.Column('tracking', sa.VARCHAR(length=60), nullable=True),
    sa.Column('is_main', sa.BOOLEAN(), nullable=True),
    sa.Column('stats', sa.INTEGER(), nullable=True),
    sa.Column('dojo', sa.SMALLINT(), nullable=True),
    sa.Column('ba', sa.SMALLINT(), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['class_name'], ['classes_enum.classes'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_foreign_key(None, 'bossing', 'characters', ['character'], ['uuid'])
    op.create_foreign_key(None, 'dailies', 'characters', ['character'], ['uuid'])
    op.create_foreign_key(None, 'farming', 'characters', ['character'], ['uuid'])
    op.create_foreign_key(None, 'progression_gear', 'characters', ['character'], ['uuid'])
    op.create_foreign_key(None, 'progression_secondary_emblem', 'characters', ['character'], ['uuid'])
    op.create_foreign_key(None, 'progression_single_field', 'characters', ['character'], ['uuid'])
    op.create_foreign_key(None, 'progression_weapons', 'characters', ['character'], ['uuid'])
    op.create_foreign_key(None, 'user_character_currency', 'characters', ['character'], ['uuid'])
    op.create_foreign_key(None, 'user_character_shops', 'characters', ['character'], ['uuid'])
    op.create_foreign_key(None, 'weeklies', 'characters', ['character'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weeklies', type_='foreignkey')
    op.drop_constraint(None, 'user_character_shops', type_='foreignkey')
    op.drop_constraint(None, 'user_character_currency', type_='foreignkey')
    op.drop_constraint(None, 'progression_weapons', type_='foreignkey')
    op.drop_constraint(None, 'progression_single_field', type_='foreignkey')
    op.drop_constraint(None, 'progression_secondary_emblem', type_='foreignkey')
    op.drop_constraint(None, 'progression_gear', type_='foreignkey')
    op.drop_constraint(None, 'farming', type_='foreignkey')
    op.drop_constraint(None, 'dailies', type_='foreignkey')
    op.drop_constraint(None, 'bossing', type_='foreignkey')
    op.drop_table('characters')
    # ### end Alembic commands ###
